services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    domainname: postgres
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_USER: testuser
      POSTGRES_DB: xa-bank
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d xa-bank"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    hostname: app
    domainname: app
    build:
      context: .
      args:
        DB_CONNECTION_STRING: "postgresql://testuser:123456789@postgres:5432/xa-bank?schema=public"
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "yarn migrate:deploy && yarn start"
